id: A7C42C5C4
title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
type: translation
pechas:
- I079AB3B8
- IE24D28CD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:03.604303
  last_modified_at: 2023-01-04 12:55:03.604327
  collections:
  - Khenpo Shenpen Nangwa Series
  - Works of Tibetan Masters
alignment_to_base:
  I079AB3B8/DDF9: 70CF
  IE24D28CD/0FFE: 70CF
